#CombatRewards-v4.1.1 config.yml
PVE-Endermite: 5
PVE-Silverfish: 5
PVE-Spider: 10
PVE-CaveSpider: 15
PVE-Slime: 15
PVE-Zombie: 20
PVE-ZombifiedPiglin: 20
PVE-Husk: 20
PVE-Phantom: 20
PVE-Drowned: 25
PVE-Skeleton: 25
PVE-Ghast: 25
PVE-Stray: 30
PVE-MagmaCube: 30
PVE-Piglin: 30
PVE-Vex: 40
PVE-Hoglin: 40
PVE-Zoglin: 45
PVE-Witch: 50
PVE-Shulker: 50
PVE-Creeper: 60
PVE-PiglinBrute: 60
PVE-Blaze: 75
PVE-Pillager: 75
PVE-Enderman: 80
PVE-WitherSkeleton: 90
PVE-Vindicator: 90
PVE-Evoker: 100
PVE-Ravager: 120
PVE-Guardian: 125
PVE-ElderGuardian: 200
PVE-Wither: 300
PVE-EnderDragon: 500
PVP-RewardEnabled: true
PVP-Reward: 500
PVP-DeathCostRegular: 500
PVP-DeathCostReduced: 50
PVP-CostOnlyInPVP: false
PVP-DropPlayerHead: true
