#CombatRewards-v4.0.8 config.yml
PVE-RewardTier01: 5
PVE-RewardTier02: 25
PVE-RewardTier03: 35
PVE-RewardTier04: 60
PVE-RewardTier05: 75
PVE-RewardTier06: 100
PVE-RewardTier07: 125
PVE-RewardTier08: 140
PVE-RewardTier09: 175
PVE-RewardTier10: 300
PVE-RewardTier11: 500
PVE-RewardTier12: 3000
PVP-Reward: 500
PVP-DeathCostRegular: 500
PVP-DeathCostReduced: 50
PVP-DeathCostOnlyInPVP: false
PVP-DropHead: true
